# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbstata',
                'doc_host': 'https://hugetim.github.io',
                'git_url': 'https://github.com/hugetim/nbstata',
                'lib_path': 'nbstata'},
  'syms': {'nbstata.helpers': {'nbstata.helpers.InVar': ('helpers.html#invar', 'nbstata/helpers.py')}}}
