# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_misc_utils.ipynb.

# %% auto 0
__all__ = ['print_red', 'DivertedPrints']

# %% ../nbs/01_misc_utils.ipynb 3
import sys
from io import StringIO

# %% ../nbs/01_misc_utils.ipynb 4
def print_red(text):
    print(f"\x1b[31m{text}\x1b[0m")

# %% ../nbs/01_misc_utils.ipynb 7
class DivertedPrints:
    """A context manager for suppressing `print` output"""
    def __enter__(self):
        self._original_stdout = sys.stdout
        self.diverted = StringIO()
        sys.stdout = self.diverted
        return self.diverted
    def __exit__(self, exc_type, exc_val, exc_tb):
        sys.stdout = self._original_stdout
        self.diverted.close()
